import { xdr } from "@stellar/stellar-sdk";
import { Client } from "@stellar/stellar-sdk/contract";
import * as fs from "fs";
import * as path from "path";
import { BindingGeneratorOptions, NETWORK_CONFIGS } from "./types";

/**
 * BindingGenerator
 *
 * Reads a deployed Soroban contract's on-chain spec and generates a
 * TypeScript class with one typed method per contract function. Each
 * generated method delegates to ContractSimulator + ArgEncoder, so the
 * generated file has no Stellar SDK dependency of its own.
 *
 * Type mapping (no on-chain data — struct/union/enum UDTs cannot be
 * resolved to real TS shapes without also generating their definitions,
 * which is out of scope here): Bool -> boolean; U32/I32 -> number;
 * U64/I64/U128/I128/U256/I256/Timepoint/Duration -> string; Address/
 * Symbol/String/Bytes/BytesN -> string; Vec<T> -> T[]; Option<T> ->
 * T | undefined; Map<K,V> -> Record<string, V>; Tuple -> a TS tuple;
 * Result<T,_> -> T; Udt -> any (its name is kept in a comment).
 *
 * @example
 * ```ts
 * const gen = new BindingGenerator({
 *   contractId: "CXXXXXX...",
 *   outputDir: "./generated",
 *   network: "testnet",
 * });
 * await gen.generate();
 * // Writes: ./generated/CXXXXXX_bindings.ts
 * ```
 */
export class BindingGenerator {
  private options: BindingGeneratorOptions;

  constructor(options: BindingGeneratorOptions) {
    this.options = options;
  }

  /**
   * Fetch the contract's spec from the network and generate TypeScript bindings.
   */
  async generate(): Promise<string> {
    const config = NETWORK_CONFIGS[this.options.network];
    const client = await Client.from({
      contractId: this.options.contractId,
      networkPassphrase: config.networkPassphrase,
      rpcUrl: config.rpcUrl,
      allowHttp: this.options.network === "local",
    });

    const content = this.buildBindings(this.options.contractId, client.spec.funcs());
    this.write(content);
    return content;
  }

  /**
   * Generate the TypeScript source for a contract from its already-parsed
   * function specs. Pure — no network access — so it can be tested in
   * isolation with hand-built XDR fixtures.
   */
  buildBindings(contractId: string, funcs: xdr.ScSpecFunctionV0[]): string {
    const methods = funcs.map((f) => this.buildMethod(f)).join("\n\n");

    return `/**
 * Auto-generated TypeScript bindings for Soroban contract
 * Contract ID: ${contractId}
 * Generated by @soroban-devkit/core BindingGenerator
 *
 * DO NOT EDIT MANUALLY — regenerate with: sdev bindings generate
 */

import { ContractSimulator, ArgEncoder, SimulationResult, Network, NetworkConfig } from "@soroban-devkit/core";

export const CONTRACT_ID = "${contractId}";

export class GeneratedContract {
  private simulator: ContractSimulator;
  private encoder = new ArgEncoder();
  private contractId: string;

  constructor(network: Network | NetworkConfig, contractId: string = CONTRACT_ID) {
    this.simulator = new ContractSimulator(network);
    this.contractId = contractId;
  }
${methods ? "\n" + methods + "\n" : ""}}
`;
  }

  /**
   * Build one typed method for a single contract function.
   */
  private buildMethod(func: xdr.ScSpecFunctionV0): string {
    const name = func.name().toString();
    const inputs = func.inputs();

    const params = inputs.map((i) => `${i.name().toString()}: ${this.scSpecTypeToTs(i.type())}`);
    params.push("caller: string");

    const argNames = inputs.map((i) => i.name().toString());

    return `  async ${name}(${params.join(", ")}): Promise<SimulationResult> {
    return this.simulator.simulate(
      this.contractId,
      "${name}",
      this.encoder.encodeArgs([${argNames.join(", ")}]),
      caller
    );
  }`;
  }

  /**
   * Map a contract spec type to its TypeScript equivalent.
   * Public so it can be tested in isolation without a network call.
   */
  scSpecTypeToTs(type: xdr.ScSpecTypeDef): string {
    const kind = type.switch();

    switch (kind) {
      case xdr.ScSpecType.scSpecTypeBool():
        return "boolean";

      case xdr.ScSpecType.scSpecTypeVoid():
      case xdr.ScSpecType.scSpecTypeVal():
        return "void";

      case xdr.ScSpecType.scSpecTypeU32():
      case xdr.ScSpecType.scSpecTypeI32():
        return "number";

      case xdr.ScSpecType.scSpecTypeU64():
      case xdr.ScSpecType.scSpecTypeI64():
      case xdr.ScSpecType.scSpecTypeU128():
      case xdr.ScSpecType.scSpecTypeI128():
      case xdr.ScSpecType.scSpecTypeU256():
      case xdr.ScSpecType.scSpecTypeI256():
      case xdr.ScSpecType.scSpecTypeTimepoint():
      case xdr.ScSpecType.scSpecTypeDuration():
        return "string";

      case xdr.ScSpecType.scSpecTypeAddress():
      case xdr.ScSpecType.scSpecTypeSymbol():
      case xdr.ScSpecType.scSpecTypeString():
      case xdr.ScSpecType.scSpecTypeBytes():
        return "string";

      case xdr.ScSpecType.scSpecTypeBytesN():
        return "string";

      case xdr.ScSpecType.scSpecTypeOption():
        return `${this.scSpecTypeToTs(type.option().valueType())} | undefined`;

      case xdr.ScSpecType.scSpecTypeResult():
        return this.scSpecTypeToTs(type.result().okType());

      case xdr.ScSpecType.scSpecTypeVec():
        return `${this.scSpecTypeToTs(type.vec().elementType())}[]`;

      case xdr.ScSpecType.scSpecTypeMap():
        return `Record<string, ${this.scSpecTypeToTs(type.map().valueType())}>`;

      case xdr.ScSpecType.scSpecTypeTuple():
        return `[${type
          .tuple()
          .valueTypes()
          .map((t) => this.scSpecTypeToTs(t))
          .join(", ")}]`;

      case xdr.ScSpecType.scSpecTypeUdt():
        // Struct/union/enum UDTs need their own generated definitions to be
        // fully typed; that's a separate, larger feature. Keep the name
        // visible so a contributor knows what to look up.
        return `any /* ${type.udt().name().toString()} */`;

      default:
        return "unknown";
    }
  }

  private write(content: string): void {
    const dir = path.resolve(this.options.outputDir);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    const filename = path.join(dir, `${this.options.contractId.slice(0, 8)}_bindings.ts`);
    fs.writeFileSync(filename, content, "utf-8");
  }
}
