import { SorobanRpc, xdr } from "@stellar/stellar-sdk";
import * as fs from "fs";
import * as path from "path";
import { BindingGeneratorOptions, NETWORK_CONFIGS } from "./types";

/**
 * BindingGenerator
 *
 * Reads a deployed Soroban contract's on-chain WASM spec and generates
 * strongly-typed TypeScript bindings, eliminating hand-written XDR boilerplate.
 *
 * @example
 * ```ts
 * const gen = new BindingGenerator({
 *   contractId: "CXXXXXX...",
 *   outputDir: "./generated",
 *   network: "testnet",
 * });
 * await gen.generate();
 * // Writes: ./generated/CXXXXXX_bindings.ts
 * ```
 */
export class BindingGenerator {
  private options: BindingGeneratorOptions;
  private server: SorobanRpc.Server;

  constructor(options: BindingGeneratorOptions) {
    this.options = options;
    const config = NETWORK_CONFIGS[options.network];
    this.server = new SorobanRpc.Server(config.rpcUrl, {
      allowHttp: options.network === "local",
    });
  }

  /**
   * Fetch contract spec from the network and generate TypeScript bindings.
   * Full WASM spec parsing is a contributor task — see GitHub issue #15.
   */
  async generate(): Promise<string> {
    const contractAddress = xdr.ScAddress.scAddressTypeContract(
      Buffer.from(this.options.contractId, "hex")
    );

    const contractCodeKey = xdr.LedgerKey.contractData(
      new xdr.LedgerKeyContractData({
        contract: contractAddress,
        key: xdr.ScVal.scvLedgerKeyContractInstance(),
        durability: xdr.ContractDataDurability.persistent(),
      })
    );

    const response = await this.server.getLedgerEntries(contractCodeKey);

    if (!response.entries?.length) {
      throw new Error(`Contract not found on network: ${this.options.contractId}`);
    }

    // TODO: Parse the WASM spec XDR to extract function signatures.
    // See: https://github.com/soroban-devkit/soroban-devkit-core/issues/15
    const content = this.buildScaffold(this.options.contractId);
    this.write(content);
    return content;
  }

  private buildScaffold(contractId: string): string {
    return `/**
 * Auto-generated TypeScript bindings for Soroban contract
 * Contract ID: ${contractId}
 * Generated by @soroban-devkit/core BindingGenerator
 *
 * ⚠️  This is a scaffold. Full method signatures require WASM spec parsing.
 *    Track progress: https://github.com/soroban-devkit/soroban-devkit-core/issues/15
 *
 * DO NOT EDIT MANUALLY — regenerate with: sdev bindings generate
 */

import {
  Contract,
  SorobanRpc,
  TransactionBuilder,
  Account,
  BASE_FEE,
} from "@stellar/stellar-sdk";

export const CONTRACT_ID = "${contractId}";

export class GeneratedContract {
  private contract: Contract;
  private server: SorobanRpc.Server;
  private networkPassphrase: string;

  constructor(rpcUrl: string, networkPassphrase: string) {
    this.contract = new Contract(CONTRACT_ID);
    this.server = new SorobanRpc.Server(rpcUrl);
    this.networkPassphrase = networkPassphrase;
  }

  // Generated method stubs will appear here after spec parsing is implemented.
  // See: https://github.com/soroban-devkit/soroban-devkit-core/issues/15
}
`;
  }

  private write(content: string): void {
    const dir = path.resolve(this.options.outputDir);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    const filename = path.join(dir, `${this.options.contractId.slice(0, 8)}_bindings.ts`);
    fs.writeFileSync(filename, content, "utf-8");
  }
}
